
const D=window.BAC_DATA;
const KEY="EBS_ULTRA_2026";
let S=JSON.parse(localStorage.getItem(KEY)||'{"xp":0,"streak":1,"hearts":5,"learned":{},"favorites":[],"wrong":[],"quiz":0,"examBest":0,"daily":"","dailyDone":false}');
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function speak(t){if(!("speechSynthesis"in window)){toast("النطق غير متاح في هذا المتصفح");return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-GB";u.rate=.8;speechSynthesis.speak(u)}
function toast(t){let x=$("#toast");if(!x)return;x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1700)}
function allWords(){return D.units.flatMap(u=>u.words.map(w=>({...w,unitId:u.id,unit:u.title}))).concat(D.general.map(w=>({...w,unitId:"G",unit:"بنك عام"})))}
function totals(){return {words:allWords().length,learned:Object.values(S.learned).reduce((a,b)=>a+b,0)}}
function learn(id){S.learned[id]=(S.learned[id]||0)+1;S.xp+=5;save();toast("+5 XP — أحسنت!");update()}
function fav(en){let i=S.favorites.indexOf(en);if(i>=0){S.favorites.splice(i,1);toast("أزيلت من المفضلة")}else{S.favorites.push(en);toast("أضيفت للمفضلة ⭐")}save();render()}
function update(){let t=totals();$("#xp")&&( $("#xp").textContent=S.xp);$("#hearts")&&($("#hearts").textContent=S.hearts);$("#streak")&&($("#streak").textContent=S.streak);$("#words")&&($("#words").textContent=t.words);$("#learned")&&($("#learned").textContent=t.learned);$("#best")&&($("#best").textContent=S.examBest)}
function unitCard(u){let n=S.learned[u.id]||0,p=Math.min(100,n/u.words.length*100);return `<button class="unit" onclick="go('learn',${u.id})"><div class="unit-no"><span class="num">${u.id}</span><span class="tag">${u.words.length} كلمة</span></div><h3>${esc(u.title)}</h3><p>${esc(u.ar)}</p><div class="unit-foot"><span>التقدم</span><span>${Math.round(p)}%</span></div><div class="bar"><i style="width:${p}%"></i></div></button>`}
function header(){return `<header class="top"><button class="brand" onclick="go('home')" style="border:0;background:transparent;color:#fff"><span class="mark">EN</span><span><b>English Bac Syria</b><small>منصة البكالوريا الذكية · 2026</small></span></button><div class="stats"><span class="pill">🔥 <b id="streak">${S.streak}</b></span><span class="pill">⭐ <b id="xp">${S.xp}</b></span><span class="pill">❤️ <b id="hearts">${S.hearts}</b></span></div></header>`}
function bottom(route){let a=[["home","🏠","الرئيسية"],["words","📚","الكلمات"],["learn","🎯","تعلّم"],["quiz","🧠","اختبار"],["exam","🏆","امتحان"],["more","☰","المزيد"]];return `<nav class="bottom">${a.map(x=>`<button class="${route===x[0]?'active':''}" onclick="go('${x[0]}')">${x[0]==='home'?'🏠':x[0]==='words'?'📚':x[0]==='learn'?'🎯':x[0]==='quiz'?'🧠':x[0]==='exam'?'🏆':'☰'}<span>${x[2]}</span></button>`).join("")}</nav>`}
function shell(route,body){document.body.innerHTML=`<div id="toast" class="toast"></div><div class="app">${header()}${body}</div>${bottom(route)}`;update()}
function home(){let t=totals();shell("home",`<section class="hero"><div class="eyebrow">منهج البكالوريا العلمي السوري · 2026</div><h1>حوّل دراسة الإنكليزي إلى لعبة. 🚀</h1><p>تعلم المفردات، اسمع النطق، اختبر نفسك، راجع أخطاءك، وتابع تقدمك من مكان واحد. الموقع مصمم للموبايل أولاً وبنية قابلة للتوسع إلى منصة تعليمية كاملة.</p><div class="actions"><button class="btn primary" onclick="go('learn')">ابدأ الآن 🎯</button><button class="btn" onclick="go('words')">بنك الكلمات 📚</button><button class="btn ghost" onclick="go('exam')">امتحان تجريبي 🏆</button></div></section><div class="metrics"><div class="metric"><b id="words">${t.words}</b><span>كلمة تعليمية</span></div><div class="metric"><b>12</b><span>وحدة منهجية</span></div><div class="metric"><b>18</b><span>موضوع قواعد</span></div><div class="metric"><b id="learned">${t.learned}</b><span>كلمة متعلمة</span></div><div class="metric"><b id="best">${S.examBest}</b><span>أفضل امتحان</span></div></div><div class="section"><div class="daily"><div><b>🔥 تحدّي اليوم</b><div class="muted">احفظ 5 كلمات ثم اختبر نفسك.</div></div><button class="btn primary" onclick="go('learn')">ابدأ التحدي</button></div></div><div class="section"><div class="section-head"><h2>الوحدات الدراسية</h2><span class="muted">اختر أي وحدة</span></div><div class="units">${D.units.map(unitCard).join("")}</div></div><div class="section"><div class="section-head"><h2>مركز الطالب</h2></div><div class="cards"><button class="feature" onclick="go('words')"><span class="ico">📚</span><b>قاموس المنهج</b><span>بحث عربي/إنكليزي + نطق + مفضلة</span></button><button class="feature" onclick="go('learn')"><span class="ico">🎧</span><b>التعلّم الصوتي</b><span>اسمع الكلمة وكررها بصوتك</span></button><button class="feature" onclick="go('grammar')"><span class="ico">📖</span><b>Grammar Lab</b><span>القواعد مع أمثلة وتطبيق</span></button><button class="feature" onclick="go('writing')"><span class="ico">✍️</span><b>Writing Coach</b><span>تدريب على مواضيع البكالوريا</span></button></div></div>`)}
function words(){shell("words",`<div class="section-head"><h2>📚 بنك الكلمات</h2><span class="muted" id="wc"></span></div><div class="panel"><div class="search"><input id="search" placeholder="اكتب كلمة بالعربي أو English..."><select id="unit" class="select"><option value="all">كل الوحدات</option><option value="G">البنك العام</option>${D.units.map(u=>`<option value="${u.id}">وحدة ${u.id} · ${u.title}</option>`).join("")}</select></div><div id="wg" class="word-grid"></div></div>`);$("#search").oninput=renderWords;$("#unit").onchange=renderWords;renderWords()}
function renderWords(){let q=($("#search")?.value||"").trim().toLowerCase(),u=$("#unit")?.value||"all";let a=allWords().filter(w=>(u==="all"||w.unitId===u)&&(!q||w.en.toLowerCase().includes(q)||w.ar.includes(q)));$("#wc").textContent=a.length+" نتيجة";$("#wg").innerHTML=a.slice(0,240).map(w=>`<article class="word"><div class="wordtop"><div><div class="en">${esc(w.en)}</div><div class="ar">${esc(w.ar)}</div></div><span class="tag">${w.unitId==="G"?"عام":"و"+w.unitId}</span></div><div class="word-actions"><button class="mini" onclick="speak('${esc(w.en).replace(/'/g,"\\'")}')">🔊 اسمع</button><button class="mini" onclick="fav('${esc(w.en).replace(/'/g,"\\'")}')">⭐ حفظ</button></div></article>`).join("")||`<div class="empty">ما في نتائج. جرّب كلمة ثانية.</div>`}
let learnState={unit:"1",i:0,show:false};
function learnPage(){let id=new URLSearchParams(location.hash.split("?")[1]||"").get("unit")||learnState.unit;learnState.unit=id;let u=D.units.find(x=>x.id===String(id))||D.units[0],w=u.words[learnState.i%u.words.length];shell("learn",`<div class="layout"><aside class="side"><b>الوحدات</b>${D.units.map(x=>`<button class="${x.id===u.id?'active':''}" onclick="learnState={unit:'${x.id}',i:0,show:false};learnPage()">📘 ${x.id}. ${esc(x.title)}</button>`).join("")}</aside><main class="panel"><div class="lesson"><span class="tag">الوحدة ${u.id} · ${esc(u.ar)}</span><div class="big">${esc(w.en)}</div><button class="speaker" onclick="speak('${esc(w.en).replace(/'/g,"\\'")}')">🔊</button><div class="muted">اسمع الكلمة مرتين، ثم حاول لفظها.</div><div class="translation" style="visibility:${learnState.show?'visible':'hidden'}">${esc(w.ar)}</div><div class="actions" style="justify-content:center;margin-top:18px"><button class="btn" onclick="learnState.show=true;learnPage()">👁️ أظهر الترجمة</button><button class="btn green" onclick="learn('${u.id}');nextLearn()">✓ حفظتها</button><button class="btn primary" onclick="nextLearn()">التالي →</button></div><div class="bar" style="margin-top:25px"><i style="width:${((learnState.i%u.words.length)+1)/u.words.length*100}%"></i></div><p class="muted">${(learnState.i%u.words.length)+1} / ${u.words.length}</p></div><div class="section"><div class="daily"><div><b>اختبر هذه الوحدة</b><div class="muted">10 أسئلة سريعة على مفردات الوحدة.</div></div><button class="btn primary" onclick="go('quiz',${u.id})">ابدأ الاختبار</button></div></div></main></div>`)}
function nextLearn(){learnState.i++;learnState.show=false;learnPage()}
let quizState={pool:[],i:0,score:0,unit:null};
function startQuiz(unit){quizState.unit=unit||null;quizState.pool=(unit?D.units.find(u=>u.id===String(unit)).words:allWords()).sort(()=>Math.random()-.5).slice(0,10);quizState.i=0;quizState.score=0;quizPage()}
function quizPage(){if(!quizState.pool.length){startQuiz();return}if(quizState.i>=quizState.pool.length){let sc=quizState.score;quizState.pool=[];shell("quiz",`<div class="result"><div class="score">${sc}/10</div><h2>انتهى الاختبار 🎉</h2><p class="muted">كل إجابة صحيحة تمنحك 10 XP. الأخطاء تُحفظ للمراجعة.</p><div class="actions" style="justify-content:center"><button class="btn primary" onclick="startQuiz(${quizState.unit||'null'})">إعادة الاختبار</button><button class="btn" onclick="go('words')">مراجعة الكلمات</button></div></div>`);return}let target=quizState.pool[quizState.i],opts=[target,...allWords().filter(w=>w.en!==target.en).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell("quiz",`<main class="panel exam"><span class="tag">سؤال ${quizState.i+1} / 10</span><h2 class="question">ما ترجمة <b>${esc(target.en)}</b>؟</h2><button class="speaker" onclick="speak('${esc(target.en).replace(/'/g,"\\'")}')">🔊</button><div class="choices">${opts.map(o=>`<button class="choice" onclick="answerQuiz(this,${o.en===target.en},'${esc(target.en).replace(/'/g,"\\'")}')">${esc(o.ar)}</button>`).join("")}</div><div class="bar" style="margin-top:22px"><i style="width:${quizState.i/10*100}%"></i></div></main>`)}
function answerQuiz(btn,ok,en){document.querySelectorAll(".choice").forEach(x=>x.disabled=true);btn.classList.add(ok?"correct":"wrong");if(ok){quizState.score++;S.xp+=10;toast("+10 XP — إجابة صحيحة")}else{S.hearts=Math.max(0,S.hearts-1);if(!S.wrong.includes(en))S.wrong.push(en);toast("راجع هذه الكلمة لاحقًا")}S.quiz++;save();update();setTimeout(()=>{quizState.i++;quizPage()},650)}
function grammar(){shell("grammar",`<div class="hero"><div class="eyebrow">Grammar Lab</div><h1>القواعد التي تحتاجها للامتحان.</h1><p>شرح مختصر، مثال واضح، ثم يمكن تحويل كل قاعدة إلى مجموعة تمارين مستقلة في النسخة القادمة.</p></div><div class="grammar">${D.grammar.map((g,i)=>`<article class="gcard"><span class="tag">قاعدة ${i+1}</span><h3>${esc(g.title)}</h3><div class="muted">${esc(g.ar)}</div><p>${esc(g.desc)}</p><div class="example">${esc(g.example)} <button class="mini" onclick="speak('${esc(g.example).replace(/'/g,"\\'")}')">🔊</button></div></article>`).join("")}</div>`)}
let exState={i:0,score:0};
const examQs=[
["Choose the correct meaning of <b>achieve</b>.",["يحقق","يفشل","يؤخر","يتجاهل"],0],
["Choose the correct meaning of <b>prevent</b>.",["يسمح","يمنع","يشرح","ينسى"],1],
["If I study hard, I ____ the exam.",["pass","passed","would pass","passing"],0],
["The bridge ____ in 2010.",["built","was built","is build","has build"],1],
["He said that he ____ tired.",["is","was","will be","has"],1],
["She arrived ___ 8 o'clock.",["in","on","at","for"],2],
["I wish I ____ more time.",["have","had","will have","am having"],1],
["The doctor made a careful ____.",["diagnosis","citizen","algorithm","tradition"],0],
["A reliable source is a source you can ____.",["verify","ignore","destroy","avoid"],0],
["Choose the closest meaning of <b>opportunity</b>.",["فرصة","عقوبة","قانون","مشكلة"],0]
];
function exam(){if(exState.i>=examQs.length){let sc=exState.score;S.examBest=Math.max(S.examBest,sc);S.xp+=sc*15;save();shell("exam",`<div class="result"><div class="score">${sc}/10</div><h2>أنهيت الامتحان 🏆</h2><p class="muted">أفضل نتيجة محفوظة على جهازك: ${S.examBest}/10</p><div class="actions" style="justify-content:center"><button class="btn primary" onclick="exState={i:0,score:0};exam()">إعادة</button><button class="btn" onclick="go('home')">الرئيسية</button></div></div>`);return}let [q,o,c]=examQs[exState.i];shell("exam",`<main class="panel exam"><span class="tag">Mock Exam · ${exState.i+1}/10</span><h2 class="question">${q}</h2><div class="examopts">${o.map((x,j)=>`<button class="choice" onclick="answerExam(this,${j===c})">${x}</button>`).join("")}</div><div class="bar" style="margin-top:20px"><i style="width:${exState.i/10*100}%"></i></div></main>`)}
function answerExam(btn,ok){document.querySelectorAll(".choice").forEach(x=>x.disabled=true);btn.classList.add(ok?"correct":"wrong");if(ok)exState.score++;else S.hearts=Math.max(0,S.hearts-1);save();update();setTimeout(()=>{exState.i++;exam()},600)}
function writing(){let topics=["The importance of education in our lives","How technology can help students","The importance of protecting the environment","A successful person who inspires you","The value of volunteering in society"];let t=topics[Math.floor(Math.random()*topics.length)];shell("more",`<div class="panel"><span class="tag">Writing Coach</span><h2>✍️ ${t}</h2><p class="muted">اكتب فقرة 70–90 كلمة. استخدم مقدمة، فكرتين واضحتين، وخاتمة.</p><div class="writing"><textarea id="essay" placeholder="Start writing here..."></textarea><div class="actions"><button class="btn primary" onclick="checkWriting()">تحليل سريع</button><button class="btn" onclick="speak('${t.replace(/'/g,"\\'")}')">🔊 اسمع الموضوع</button></div><div id="feedback"></div></div></div>`)}
function checkWriting(){let v=$("#essay").value.trim(),n=v? v.split(/\s+/).length:0;let tips=[];if(n<70)tips.push("حاول الوصول إلى 70 كلمة على الأقل.");if(n>100)tips.push("اختصر الفقرة قليلًا.");if(!/[.!?]/.test(v))tips.push("أضف علامات ترقيم.");if(/\b(because|however|therefore|also|first|finally)\b/i.test(v))tips.push("ممتاز: استخدمت روابط منطقية.");else tips.push("أضف أدوات ربط مثل because / however / therefore.");$("#feedback").innerHTML=`<div class="result"><b>${n} كلمة</b><p>${tips.join("<br>")}</p></div>`}
function more(){shell("more",`<div class="section"><div class="section-head"><h2>☰ المزيد</h2></div><div class="cards"><button class="feature" onclick="go('grammar')"><span class="ico">📖</span><b>Grammar Lab</b><span>18 قاعدة أساسية</span></button><button class="feature" onclick="writing()"><span class="ico">✍️</span><b>Writing Coach</b><span>تدريب على الكتابة</span></button><button class="feature" onclick="favorites()"><span class="ico">⭐</span><b>المفضلة</b><span>الكلمات التي حفظتها</span></button><button class="feature" onclick="resetProgress()"><span class="ico">♻️</span><b>إعادة التقدم</b><span>يمسح بيانات هذا الجهاز</span></button></div></div>`)}
function favorites(){let a=allWords().filter(w=>S.favorites.includes(w.en));shell("more",`<div class="section-head"><h2>⭐ كلماتي المحفوظة</h2><span class="muted">${a.length}</span></div><div class="word-grid">${a.map(w=>`<article class="word"><div class="en">${esc(w.en)}</div><div class="ar">${esc(w.ar)}</div><div class="word-actions"><button class="mini" onclick="speak('${esc(w.en).replace(/'/g,"\\'")}')">🔊 اسمع</button><button class="mini" onclick="fav('${esc(w.en).replace(/'/g,"\\'")}')">حذف</button></div></article>`).join("")||`<div class="empty">ما حفظت كلمات بعد.</div>`}</div>`)}
function resetProgress(){if(confirm("متأكد؟ سيتم حذف التقدم من هذا الجهاز.")){localStorage.removeItem(KEY);location.reload()}}
function go(route,arg){if(route==="home")home();else if(route==="words")words();else if(route==="learn"){learnState={unit:String(arg||"1"),i:0,show:false};learnPage()}else if(route==="quiz")startQuiz(arg);else if(route==="grammar")grammar();else if(route==="exam"){exState={i:0,score:0};exam()}else if(route==="writing")writing();else more();window.scrollTo(0,0)}
window.addEventListener("load",()=>home());
