const D=window.BAC_DATA;
const LISTENING=window.BAC_LISTENING;
const KEY='EBS_PRO_2026';
const defaultState={xp:0,streak:1,hearts:5,learned:{},favorites:[],wrong:[],quiz:0,examBest:0,dictationBest:{},lastUnit:'1'};
let S=Object.assign({},defaultState,JSON.parse(localStorage.getItem(KEY)||'{}'));
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s||'').toLowerCase().replace(/[’‘`]/g,"'").replace(/[^a-z0-9'\s]/g,' ').replace(/\s+/g,' ').trim();
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function speak(t){if(!('speechSynthesis'in window))return toast('النطق غير متاح في هذا المتصفح');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.82;u.pitch=1;speechSynthesis.speak(u)}
function allEntries(){return [...D.units.flatMap(u=>u.words.map(w=>({...w,unitId:u.id,unit:u.title,source:'وحدة '+u.id}))),...(D.general||[]).map(w=>({...w,unitId:'G',unit:'البنك الشامل',source:w.source||'البنك الشامل'}))]}
function uniqueWords(){const m=new Map();for(const w of allEntries()){const k=norm(w.en);if(!k)continue;if(!m.has(k))m.set(k,{...w,units:new Set([w.unitId]),sources:new Set([w.source||w.unit])});else{m.get(k).units.add(w.unitId);m.get(k).sources.add(w.source||w.unit);if(!m.get(k).ar&&w.ar)m.get(k).ar=w.ar}}return [...m.values()].map(w=>({...w,units:[...w.units],sources:[...w.sources]}))}
const WORDS=uniqueWords();
function stats(){return {entries:allEntries().length,unique:WORDS.length,learned:Object.keys(S.learned).filter(k=>S.learned[k]>0).length,favs:S.favorites.length,wrong:S.wrong.length}}
function header(){const t=stats();return `<header class="top"><button class="brand" onclick="go('home')"><span class="mark">EN</span><span><b>English Bac Syria</b><small>منصة البكالوريا الذكية · 2026</small></span></button><div class="stats"><span class="pill">🔥 <b id="streak">${S.streak}</b></span><span class="pill">⭐ <b id="xp">${S.xp}</b></span><span class="pill">❤️ <b id="hearts">${S.hearts}</b></span></div></header>`}
function bottom(route){const a=[['home','⌂','الرئيسية'],['words','▦','الكلمات'],['learn','◎','تعلّم'],['dictation','◉','استماع'],['quiz','?','اختبار'],['more','☰','المزيد']];return `<nav class="bottom"><div class="bottom-inner">${a.map(x=>`<button class="${route===x[0]?'active':''}" onclick="go('${x[0]}')"><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join('')}</div></nav>`}
function shell(route,body){document.body.innerHTML=`<div id="toast" class="toast"></div><div class="app">${header()}${body}</div>${bottom(route)}`;window.scrollTo({top:0,behavior:'smooth'})}
function updateHeader(){const t=stats();$('#xp')&&($('#xp').textContent=S.xp);$('#hearts')&&($('#hearts').textContent=S.hearts);$('#streak')&&($('#streak').textContent=S.streak);$('#entryCount')&&($('#entryCount').textContent=t.entries.toLocaleString());$('#uniqueCount')&&($('#uniqueCount').textContent=t.unique.toLocaleString());$('#learnedCount')&&($('#learnedCount').textContent=t.learned)}
function progressForUnit(u){const n=Object.keys(S.learned).filter(k=>k.startsWith(u.id+'::')).length;return Math.min(100,n/Math.max(1,u.words.length)*100)}
function unitCard(u){const p=progressForUnit(u);return `<button class="unit" onclick="go('learn','${u.id}')"><div class="unit-top"><span class="num">${u.id}</span><span class="tag green-tag">${u.words.length} أساسية</span></div><h3>${esc(u.title)}</h3><p>${esc(u.ar)}</p><div class="unit-foot"><span>تقدمك</span><b>${Math.round(p)}%</b></div><div class="bar"><i style="width:${p}%"></i></div></button>`}
function home(){const t=stats();shell('home',`<section class="hero"><div class="eyebrow">🇸🇾 للثالث الثانوي العلمي · English Bac Syria</div><h1>إنكليزي البكالوريا، بطريقة أقرب لتطبيق تعلّم حقيقي.</h1><p>مفردات مترجمة، نطق، مراجعة ذكية، اختبارات، واستماع مع تدقيق فعلي. كل تقدم تحفظه المنصة على جهازك.</p><div class="actions"><button class="btn primary" onclick="go('learn')">ابدأ التعلّم</button><button class="btn" onclick="go('dictation')">🎧 اختبار استماع</button><button class="btn ghost" onclick="go('quiz')">🧠 اختبر نفسك</button></div></section><section class="metrics"><div class="metric"><b id="entryCount">${t.entries.toLocaleString()}</b><span>مدخل في البنك</span></div><div class="metric"><b id="uniqueCount">${t.unique.toLocaleString()}</b><span>كلمة/عبارة فريدة</span></div><div class="metric"><b>12</b><span>وحدة</span></div><div class="metric"><b>18</b><span>قاعدة</span></div><div class="metric"><b id="learnedCount">${t.learned}</b><span>تعلمتها</span></div></section><section class="section"><div class="daily"><div><b>🎧 أهم ميزة جديدة: التدقيق الحقيقي</b><span>اسمع المقطع كاملًا، اكتب ما تسمعه، ثم اضغط «تدقيق» ليتم احتساب الكلمات الصحيحة والخاطئة فعليًا.</span></div><button class="btn primary" onclick="go('dictation')">جرّبها الآن</button></div></section><section class="section"><div class="section-head"><h2>الوحدات الدراسية</h2><span class="muted">عدد الكلمات هنا هو العدد المرتبط بالوحدة فقط، وليس إجمالي البنك.</span></div><div class="units">${D.units.map(unitCard).join('')}</div></section><section class="section"><div class="section-head"><h2>مركز الطالب</h2><span class="muted">كل شيء من شريط واحد ثابت</span></div><div class="cards"><button class="feature" onclick="go('words')"><span class="ico">▦</span><b>بنك الكلمات</b><span>بحث بلا تكرار + فلترة + نطق</span></button><button class="feature" onclick="go('learn')"><span class="ico">◎</span><b>تعلم تدريجي</b><span>بطاقات ومراجعة وتقدم</span></button><button class="feature" onclick="go('dictation')"><span class="ico">◉</span><b>Listening Lab</b><span>مقطع كامل + تدقيق كلمة بكلمة</span></button><button class="feature" onclick="go('quiz')"><span class="ico">?</span><b>اختبار ذكي</b><span>الخطأ يحفظ للمراجعة</span></button></div></section>`);updateHeader()}
let wordPage=1,wordFilter='all',wordQuery='';
function words(){wordPage=1;wordFilter='all';wordQuery='';shell('words',`<section class="section-head"><div><h2>▦ بنك الكلمات</h2><p class="muted">بحث واحد، نتيجة واحدة لكل كلمة حتى لو تكررت في أكثر من مصدر.</p></div><span class="count-badge" id="wc"></span></section><section class="panel bank"><div class="bank-stats"><span>المدخلات <b>${allEntries().length}</b></span><span>الفريدة <b>${WORDS.length}</b></span><span>المفضلة <b>${S.favorites.length}</b></span></div><div class="search-row"><input id="search" autocomplete="off" placeholder="اكتب English أو الترجمة العربية..."><select id="unit" class="select"><option value="all">كل المصادر</option><option value="G">البنك الشامل</option>${D.units.map(u=>`<option value="${u.id}">الوحدة ${u.id} · ${esc(u.title)}</option>`).join('')}</select><select id="sort" class="select"><option value="az">A → Z</option><option value="za">Z → A</option></select></div><div id="wg" class="word-grid"></div><button id="moreWords" class="load-more" onclick="loadMoreWords()">تحميل المزيد</button></section>`);$('#search').oninput=e=>{wordQuery=e.target.value;wordPage=1;renderWords()};$('#unit').onchange=e=>{wordFilter=e.target.value;wordPage=1;renderWords()};$('#sort').onchange=renderWords;renderWords()}
function renderWords(){let q=norm(wordQuery),u=wordFilter;let a=WORDS.filter(w=>(u==='all'||w.units.includes(u))&&(!q||norm(w.en).includes(q)||String(w.ar).includes(wordQuery.trim())));a.sort((x,y)=>($('#sort')?.value==='za'?-1:1)*x.en.localeCompare(y.en));const shown=a.slice(0,wordPage*48);$('#wc').textContent=`${a.length.toLocaleString()} نتيجة`;$('#wg').innerHTML=shown.map(w=>`<article class="word"><div class="wordtop"><div><div class="en">${esc(w.en)}</div><div class="ar">${esc(w.ar)}</div></div><span class="tag">${w.units.includes('G')?'عام':w.units.filter(x=>x!=='G').map(x=>'و'+x).join(' · ')}</span></div><div class="word-actions"><button class="mini" onclick="speak(${JSON.stringify(w.en)})">🔊 نطق</button><button class="mini ${S.favorites.includes(w.en)?'fav-on':''}" onclick="toggleFav(${JSON.stringify(w.en)})">★ ${S.favorites.includes(w.en)?'محفوظ':'حفظ'}</button><button class="mini" onclick="markLearned(${JSON.stringify(w.en)},${JSON.stringify(w.units[0]||'G')})">✓ أعرفها</button></div></article>`).join('')||`<div class="empty">لا توجد نتائج مطابقة.</div>`;$('#moreWords').style.display=shown.length<a.length?'block':'none'}
function loadMoreWords(){wordPage++;renderWords()}
function toggleFav(en){const i=S.favorites.indexOf(en);if(i>=0){S.favorites.splice(i,1);toast('أزيلت من المفضلة')}else{S.favorites.push(en);toast('أضيفت للمفضلة ⭐')}save();renderWords();updateHeader()}
function markLearned(en,unit){const k=String(unit)+'::'+norm(en);if(!S.learned[k]){S.learned[k]=1;S.xp+=5;toast('+5 XP — تم تسجيل الكلمة')}else toast('هذه الكلمة مسجلة عندك');save();updateHeader()}
let learnState={unit:'1',i:0,show:false};
function learnPage(){const u=D.units.find(x=>x.id===String(learnState.unit))||D.units[0];const i=learnState.i%u.words.length,w=u.words[i],k=u.id+'::'+norm(w.en);shell('learn',`<section class="layout"><aside class="side"><div class="side-title">الوحدات</div>${D.units.map(x=>`<button class="side-btn ${x.id===u.id?'active':''}" onclick="learnState={unit:'${x.id}',i:0,show:false};learnPage()"><span>${x.id}</span>${esc(x.title)}</button>`).join('')}</aside><main class="panel lesson"><span class="tag green-tag">الوحدة ${u.id} · ${esc(u.ar)}</span><div class="lesson-count">${i+1} / ${u.words.length}</div><div class="big-word">${esc(w.en)}</div><button class="speaker" onclick="speak(${JSON.stringify(w.en)})">🔊</button><div class="translation ${learnState.show?'visible':''}">${esc(w.ar)}</div><p class="muted">اسمع، حاول تذكر المعنى، ثم أظهر الترجمة.</p><div class="actions center"><button class="btn" onclick="learnState.show=true;learnPage()">إظهار المعنى</button><button class="btn green" onclick="markLearned(${JSON.stringify(w.en)},'${u.id}');nextLearn()">✓ أعرفها</button><button class="btn primary" onclick="nextLearn()">التالي</button></div><div class="bar bigbar"><i style="width:${(i+1)/u.words.length*100}%"></i></div><div class="lesson-tools"><button class="tool" onclick="go('dictation',${JSON.stringify(u.id)})">🎧 استماع الوحدة</button><button class="tool" onclick="startQuiz('${u.id}')">🧠 اختبار الوحدة</button></div></main></section>`)}
function nextLearn(){learnState.i++;learnState.show=false;learnPage()}
let quizState={pool:[],i:0,score:0,unit:null,asked:[]};
function startQuiz(unit=null){quizState={pool:(unit?D.units.find(u=>u.id===String(unit)).words.map(w=>({...w,unitId:String(unit)})):WORDS).sort(()=>Math.random()-.5).slice(0,10),i:0,score:0,unit:unit||null,asked:[]};quizPage()}
function quizPage(){if(quizState.i>=quizState.pool.length){const sc=quizState.score;S.xp+=sc*5;save();shell('quiz',`<section class="result"><div class="score">${sc} / ${quizState.pool.length}</div><h2>${sc>=8?'ممتاز جدًا 🔥':sc>=6?'جيد جدًا 👏':'نكمل المراجعة 💪'}</h2><p class="muted">تم حفظ الأخطاء للمراجعة، وكل إجابة صحيحة أضافت XP.</p><div class="actions center"><button class="btn primary" onclick="startQuiz(${quizState.unit?JSON.stringify(quizState.unit):'null'})">إعادة الاختبار</button><button class="btn" onclick="go('words')">بنك الكلمات</button><button class="btn" onclick="go('dictation')">استماع</button></div></section>`);return}const target=quizState.pool[quizState.i];quizState.asked.push(target.en);const pool=allEntries();const opts=[target,...pool.filter(w=>norm(w.en)!==norm(target.en)).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell('quiz',`<main class="panel exam"><div class="quiz-head"><span class="tag green-tag">سؤال ${quizState.i+1} / ${quizState.pool.length}</span><span>${quizState.score} صحيحة</span></div><h2 class="question">ما معنى:</h2><div class="question-word">${esc(target.en)}</div><button class="speaker" onclick="speak(${JSON.stringify(target.en)})">🔊</button><div class="choices">${opts.map(o=>`<button class="choice" onclick="answerQuiz(this,${norm(o.en)===norm(target.en)},${JSON.stringify(target.en)})">${esc(o.ar)}</button>`).join('')}</div><div class="bar"><i style="width:${quizState.i/quizState.pool.length*100}%"></i></div></main>`)}
function answerQuiz(btn,ok,en){document.querySelectorAll('.choice').forEach(x=>x.disabled=true);btn.classList.add(ok?'correct':'wrong');if(ok){quizState.score++;toast('إجابة صحيحة ✓')}else{S.hearts=Math.max(0,S.hearts-1);if(!S.wrong.includes(en))S.wrong.push(en);toast('خطأ — أضفناها لقائمة المراجعة')}S.quiz++;save();setTimeout(()=>{quizState.i++;quizPage()},650)}
function dictation(unit='1'){const u=LISTENING.find(x=>x.id===String(unit))||LISTENING[0];shell('dictation',`<section class="dictation-layout"><aside class="side"><div class="side-title">مقاطع الاستماع</div>${LISTENING.map(x=>`<button class="side-btn ${x.id===u.id?'active':''}" onclick="dictation('${x.id}')"><span>${x.id}</span>${esc(x.title)}</button>`).join('')}</aside><main class="panel dictation"><div class="dictation-head"><div><span class="tag green-tag">Listening Lab · Unit ${u.id}</span><h2>${esc(u.title)}</h2><p class="muted">اسمع المقطع كاملًا ثم اكتبه كما سمعته. التدقيق لا يحسب علامات من الفراغات أو علامات الترقيم.</p></div><div class="best">أفضل نتيجة<br><b>${S.dictationBest[u.id]||0}%</b></div></div><audio id="audio" controls preload="metadata" src="audio/unit-${u.id}.mp3"></audio><div class="audio-actions"><button class="mini" onclick="document.querySelector('#audio').play()">▶ تشغيل</button><button class="mini" onclick="document.querySelector('#audio').pause()">Ⅱ إيقاف</button><button class="mini" onclick="speak(${JSON.stringify(u.text)})">🔊 صوت الجهاز</button></div><div class="dictation-note">💡 نصيحة: اسمع مرة كاملة، ثم أعد المقطع على دفعات قصيرة، وبعدها اضغط تدقيق.</div><textarea id="answer" placeholder="اكتب المقطع الذي سمعته هنا..." spellcheck="false"></textarea><div class="dictation-actions"><button class="btn primary" onclick="checkDictation('${u.id}')">✓ تدقيق الإجابة</button><button class="btn" onclick="$('#answer').value='';$('#feedback').innerHTML=''">مسح</button></div><div id="feedback"></div></main></section>`)}
function tokens(s){return norm(s).match(/[a-z]+(?:'[a-z]+)*/g)||[]}
function checkDictation(id){const u=LISTENING.find(x=>x.id===String(id));const a=tokens($('#answer').value),b=tokens(u.text);let correct=0;const max=Math.max(a.length,b.length);for(let i=0;i<Math.min(a.length,b.length);i++)if(a[i]===b[i])correct++;const score=Math.round(correct/Math.max(1,b.length)*100);if(score>(S.dictationBest[id]||0))S.dictationBest[id]=score;S.xp+=Math.round(score/10);save();let firstErrors=[];for(let i=0;i<b.length;i++){if(a[i]!==b[i])firstErrors.push(`<span class="error-word"><b>${esc(b[i])}</b>${a[i]?` ← كتبت: ${esc(a[i])}`:' ← ناقصة'}</span>`);if(firstErrors.length>=12)break}$('#feedback').innerHTML=`<div class="dict-result ${score>=85?'great':''}"><div class="score">${score}%</div><div><b>${correct}</b> صحيحة من <b>${b.length}</b> كلمة</div><p class="muted">عدد الكلمات التي كتبتها: ${a.length}. التدقيق يقارن الكلمات بالترتيب.</p>${firstErrors.length?`<div class="errors"><b>أول الأخطاء:</b>${firstErrors.join('')}</div>`:'<div class="success">ممتاز! لم يظهر أي خطأ في الكلمات المكتوبة.</div>'}</div>`;toast(`نتيجتك ${score}%`);updateHeader()}
function grammar(){shell('more',`<section class="section-head"><div><h2>📖 Grammar Lab</h2><p class="muted">18 موضوعًا مرتبة للمراجعة السريعة.</p></div></section><div class="grammar">${(D.grammar||[]).map((g,i)=>`<article class="gcard"><span class="tag green-tag">${i+1}</span><h3>${esc(g.title)}</h3><p>${esc(g.ar)}</p><p class="muted">${esc(g.desc)}</p><div class="example">${esc(g.example)}</div></article>`).join('')}</div>`)}
function exam(){const sample=WORDS.sort(()=>Math.random()-.5).slice(0,8);shell('more',`<main class="panel exam"><span class="tag green-tag">امتحان تجريبي مصغر</span><h2>اختبر مفرداتك بسرعة</h2><p class="muted">8 أسئلة، ثم تظهر النتيجة وتُحفظ أفضل نتيجة.</p><button class="btn primary" onclick="startQuiz()">ابدأ الامتحان</button><div class="exam-grid">${sample.map((w,i)=>`<div class="exam-preview"><b>${i+1}</b><span>${esc(w.en)}</span></div>`).join('')}</div></main>`)}
function writing(){shell('more',`<section class="panel writing"><span class="tag green-tag">Writing Coach</span><h2>اكتب موضوعك</h2><p class="muted">اكتب فقرة تدريبية، وسيحسب لك عدد الكلمات ويعطيك تنبيهات أولية. هذا تدقيق لغوي مساعد وليس تصحيحًا بشريًا.</p><textarea id="writingText" placeholder="Start writing in English..."></textarea><div class="writing-bar"><span>الكلمات: <b id="writeCount">0</b></span><span>الهدف: 80 كلمة</span></div><div id="writeFeedback" class="dict-result"></div></section>`);$('#writingText').oninput=()=>{const n=tokens($('#writingText').value).length;$('#writeCount').textContent=n;$('#writeFeedback').innerHTML=n>=80?'<div class="success">وصلت إلى 80 كلمة أو أكثر ✓</div>':`<div class="muted">باقي ${80-n} كلمة للوصول إلى هدف 80.</div>`}}
function more(){shell('more',`<section class="section-head"><div><h2>☰ مركز الطالب</h2><p class="muted">الأدوات التي لا تحتاجها كل دقيقة موجودة هنا.</p></div></section><div class="more-grid"><button class="feature" onclick="grammar()"><span class="ico">📖</span><b>القواعد</b><span>18 موضوعًا</span></button><button class="feature" onclick="writing()"><span class="ico">✍️</span><b>الكتابة</b><span>هدف 80 كلمة</span></button><button class="feature" onclick="favorites()"><span class="ico">★</span><b>المفضلة</b><span>${S.favorites.length} كلمة</span></button><button class="feature" onclick="wrongWords()"><span class="ico">⚠</span><b>أخطائي</b><span>${S.wrong.length} كلمة</span></button><button class="feature danger" onclick="resetProgress()"><span class="ico">↺</span><b>إعادة التقدم</b><span>يمسح بيانات هذا الجهاز</span></button></div>`)}
function favorites(){const a=WORDS.filter(w=>S.favorites.includes(w.en));shell('more',`<section class="section-head"><h2>★ المفضلة</h2><span class="muted">${a.length}</span></section><div class="word-grid">${a.map(w=>`<article class="word"><div class="en">${esc(w.en)}</div><div class="ar">${esc(w.ar)}</div><button class="mini" onclick="speak(${JSON.stringify(w.en)})">🔊 نطق</button></article>`).join('')||'<div class="empty">لم تحفظ أي كلمة بعد.</div>'}</div>`)}
function wrongWords(){const a=WORDS.filter(w=>S.wrong.includes(w.en));shell('more',`<section class="section-head"><h2>⚠ أخطائي</h2><span class="muted">راجع هذه الكلمات أولًا.</span></section><div class="word-grid">${a.map(w=>`<article class="word"><div class="en">${esc(w.en)}</div><div class="ar">${esc(w.ar)}</div><button class="mini" onclick="speak(${JSON.stringify(w.en)})">🔊 نطق</button></article>`).join('')||'<div class="empty">لا توجد أخطاء محفوظة. ممتاز!</div>'}</div>`)}
function resetProgress(){if(confirm('سيتم حذف تقدمك من هذا الجهاز. هل أنت متأكد؟')){localStorage.removeItem(KEY);location.reload()}}
function go(route,arg){if(route==='home')home();else if(route==='words')words();else if(route==='learn'){learnState={unit:String(arg||S.lastUnit||'1'),i:0,show:false};S.lastUnit=learnState.unit;save();learnPage()}else if(route==='dictation')dictation(arg||'1');else if(route==='quiz')startQuiz(arg||null);else if(route==='grammar')grammar();else if(route==='exam')exam();else if(route==='writing')writing();else more()}
window.addEventListener('load',home);
