window.BAC_LISTENING = [
{id:'1',title:'Life Choices',ar:'خيارات الحياة',text:'Choosing a future career is an important decision. Young people need to think about their interests, skills, strengths and goals before they choose a profession. Parents can provide useful advice, but students should also learn to make independent decisions. A good career should match a person’s abilities and values. Training, experience and hard work can create new opportunities. It is normal to make mistakes while planning the future. The most important thing is to learn from experience, improve your skills and keep moving toward a clear goal.'},
{id:'2',title:'Success',ar:'النجاح',text:'Success does not usually happen in one day. It comes from effort, determination, patience and the ability to learn from failure. A student may face difficult problems, but each attempt can provide valuable experience. Confidence is important, yet successful people also understand their weaknesses and work to improve them. Small progress every day can lead to a great achievement. When a person has a clear goal, stays motivated and continues working after a mistake, failure becomes a lesson rather than an ending.'},
{id:'3',title:'Medicine',ar:'الطب',text:'Modern medicine has changed the way doctors diagnose and treat diseases. Hospitals use advanced technology to examine patients and discover health problems early. Doctors and nurses need knowledge, accuracy and responsibility because patients depend on their decisions. Medical research also helps scientists understand infections and develop better treatments. A healthy lifestyle can prevent many problems, but some illnesses require professional care. Good healthcare combines skilled workers, useful technology, careful diagnosis and suitable treatment.'},
{id:'4',title:'Engineering',ar:'الهندسة',text:'Engineers use science and mathematics to design useful structures, machines and systems. They may build bridges, inspect buildings, repair devices or develop new technologies. Safety is an important part of every engineering project. Engineers must measure carefully, understand pressure and force, and choose suitable materials. A successful design should solve a real problem while using resources responsibly. Engineering also requires creativity because a difficult problem may have several possible solutions.'},
{id:'5',title:'Civil Rights',ar:'الحقوق المدنية',text:'Civil rights protect the freedom and equality of people in society. Every citizen should have basic rights and responsibilities, including respect for the law and other people. Discrimination can prevent individuals from receiving equal opportunities. Peaceful campaigns and public discussion can help communities demand fair treatment. Governments have a responsibility to protect human rights, while citizens can participate in elections and support positive change. Justice becomes stronger when people respect differences and work together.'},
{id:'6',title:'United Nations',ar:'الأمم المتحدة',text:'The United Nations is an international organization that works with member states on global problems. Its activities include peace, security, humanitarian aid, education and development. Countries may disagree about political issues, but cooperation and negotiation can help them resolve conflicts. Refugees and people affected by war often need international support. Successful cooperation requires communication, respect and a willingness to find agreements. Global problems are difficult, so countries need to work together instead of trying to solve everything alone.'},
{id:'7',title:'Microorganisms',ar:'الكائنات الحية الدقيقة',text:'Microorganisms are tiny living things that are often too small to see without a microscope. Some bacteria and fungi can be useful, while others may cause disease or contaminate food and water. Scientists study microorganisms in laboratories to understand how they grow, reproduce and survive. Vaccines and antibiotics can help protect people from certain infections. Learning about microorganisms is important because these organisms are part of our environment and can affect human health.'},
{id:'8',title:'The Human Body',ar:'جسم الإنسان',text:'The human body is made of many organs and systems that work together. The heart pumps blood, the lungs help the body breathe, and the brain controls many activities. Bones support the body while muscles allow movement. The stomach and other organs help digest food and provide energy. Healthy habits such as regular exercise, enough sleep and balanced food can support physical and mental health. Understanding how the body works helps people make better decisions about their health.'},
{id:'9',title:'Citizenship',ar:'المواطنة',text:'Good citizenship means taking responsibility for the community and respecting other people. Citizens can participate in useful activities, volunteer, protect public places and support people who need help. Honesty, loyalty, tolerance and respect are important values. A strong community is built when people cooperate instead of thinking only about themselves. Small actions such as recycling, helping a neighbour or donating to charity can make a positive difference. Citizenship is not only a legal status; it is also a way of contributing to society.'},
{id:'10',title:'Culture Shock',ar:'الصدمة الثقافية',text:'Living in another country can be exciting, but it can also create culture shock. New customs, unfamiliar food, different behaviour and a new language may make a person feel confused or homesick. Communication and patience can make the experience easier. People can learn about local traditions while keeping their own identity and values. Respecting differences is important because no culture is exactly the same as another. With time, many people adapt, become more confident and discover that cultural differences can be an opportunity to learn.'},
{id:'11',title:'Artificial Intelligence',ar:'الذكاء الاصطناعي',text:'Artificial intelligence is changing many parts of modern life. Computers can analyse information, recognize patterns and perform tasks that once required human effort. Machine learning allows systems to improve when they receive more data. Artificial intelligence can support education, medicine, engineering and communication, but it also creates important questions about privacy, responsibility and the future of work. People should learn how these technologies operate and use them carefully. Technology is most useful when it helps people solve real problems without replacing good judgment.'},
{id:'12',title:'Digital Literacy',ar:'المحو الأمّي الرقمي',text:'Digital literacy means having the skills needed to use digital tools safely and effectively. Students should know how to search for reliable information, protect passwords, recognize suspicious messages and communicate responsibly online. Not every website or social media post is trustworthy, so users should check the source before sharing information. Digital skills can improve education and make communication easier, but technology should be used with balance. A responsible digital citizen thinks carefully, protects personal information and respects other people online.'}
];
